steps:

    # build only the first stage, so we can run tests with it
  - id: build-test-image
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --target build --tag demo:test .

  - id: run-tests
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker container run demo:test go test

  - id: build-app
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --tag gcr.io/${PROJECT_ID}/demo:${COMMIT_SHA} .

  - id: kubeval
    dir: .
    name: cloudnatived/helm-cloudbuilder
    entrypoint: sh
    args:
      - -c
      - |
        helm template ./k8s/demo/ | kubeval

images:
  - gcr.io/${PROJECT_ID}/demo:${COMMIT_SHA}
